### ISSUE TITLE
outputFolders -> outputHashGlob

### ISSUE THREAD

**Issue by kenotron** [microsoft/backfill#117]
There may be cases where there are overlaps between the folder from hashGlob and outputFolder - for example, we generate these `.scss.ts` files.

**Comment by bweggersen** [comment]
I'm not sure I understand. Do you want to use a glob to express `outputFolders`?

**Comment by kenotron** [comment]
So, we have this scenario in our world... I know it's not ideal, but we are not that unique :)

We transpile from `.scss` files to `.scss.ts` files via a build step so that we wouldn't need people to have a `sass-loader` to consume our library while letting our own devs work as if we had that capability. So, we generate `/src/**/*.scss` to `/src/**/*.scss.ts` files then we transpile. I am not sure if this belong in the `outputFolder` - things that are "intermediate"... but to be more correct, backfill should account for those as well I think. And so, I wouldn't want the entire /src folder to be inside the output, but the /src/**/*.scss.ts should be

**Comment by bweggersen** [comment]
Could you check in these intermediate files? We've done that for some generated code that needs to live in the `/src` folder.
