### ISSUE TITLE
backfill API

### ISSUE THREAD

**Issue by kenotron** [microsoft/backfill#119]
I think it would be really nice to have backfill be opened up as an API to be integrated into other tools (I would like to absorb this into `just-scripts`, for example).

I also am wondering if parts of this software can be tweaked so that it works in terms of arbitrary (like a task) dependency rather than package dependency. This would allow us to generate a top level graph of all the tasks needed to run ahead of time and analyze the cache much better.

**Comment by bweggersen** [comment]
Definitely! We should spec out the requirements to support this scenario.

**Comment by bweggersen** [comment]
Implemented by #221
